### PR TITLE
Feature/rubocop and hound

### LINKED ISSUE #8: Setup Hound
- ~~setup scss lint~~
- setup ruby lint
- ~~setup javascript lint~~
- rubocop 0.29.1 (Same as hound :disappointed:)

### PR DESCRIPTION
**Pull request by JuanitoFatas**
This pull request adds
- Add [rubocop v0.29.1](https://github.com/bbatsov/rubocop/tree/v0.29.1) for consistent ruby styles
- Enable https://houndci.com for auto-review styles on Pull Request :dog: 
- Why v0.29.1? because the [houndci service uses 0.29.1](https://github.com/thoughtbot/hound/blob/master/Gemfile#L32)
- Use default config provided [here](https://houndci.com/configuration#ruby) for `.ruby-style.yml`
- Future ruby style changes goes to `.ruby-style.yml`

How to run rubocop:

```
bundle exec rubocop -DR
```

Most important thing you need to know are probably use double quotes for String. And take a look at [this opinioned ruby style guide](https://github.com/thoughtbot/guides/tree/master/style/ruby).

Learn more about rubocop at [here](https://github.com/bbatsov/rubocop/tree/v0.29.1).

Fixes #8.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@rubytaiwan/rubyists Please take a look :eyes:

**Comment by bugtender** [comment]
I am a little confused. Why we need rubocop ?
I thought Hound CI will check the style for you so that we don't need to bundle it.

**Comment by AnNOtis** [comment]
> I am a little confused. Why we need rubocop ?
> I thought Hound CI will check the style for you so that we don't need to bundle it.

Rubocop can be used in local environment, so that we can self-checked before pushing.

**Comment by JuanitoFatas** [comment]
> Rubocop can be used in local environment, so that we can self-checked before pushing.

Exactly. :blush:

**Pull request merged**
