### PR TITLE
Setup bootstrap font awesome

### LINKED ISSUE #3: Setup bootstrap and font-awesome

### PR DESCRIPTION
**Pull request by azi**
close #3

### CODE REVIEW

**Comment by sunkai612** [comment]
looks good :+1:

**Comment by JuanitoFatas** [comment]
Thanks @azi :confetti_ball: :tada:

**Comment by azi** [comment]
:raised_hands:

**Comment by azi** [comment]
I wanna ask how to referenced this branch to other branch ?  like you do above , thanks  :smile_cat:

**Comment by JuanitoFatas** [comment]
@azi Use `#` with the number of issue or pull request, read more about it [here](https://help.github.com/articles/writing-on-github/#issue-autocompletion). :wink:

**Comment by puff-tw** [comment]
It's helpful for me.  :raised_hands:

**Pull request merged**
