### PR TITLE
Setup Code Climate

### LINKED ISSUE #12: Add codeclimate
https://codeclimate.com/github/rubytaiwan/rubytw-reboot

### PR DESCRIPTION
**Pull request by JuanitoFatas**
- Add code climate badge (See [Rendered README.md](https://github.com/rubytaiwan/rubytw-reboot/blob/8a605a524bcbd35189ed4de50f8f760909642340/README.md))
- Add code climate to travis.yml for reporting test coverage

Fixes #12

### CODE REVIEW

**Comment by puff-tw** [comment]
I found this, need encrypt it?
[Encrypt your Code Climate repo token for public repositories on Travis CI](https://coderwall.com/p/5mtq6q/encrypt-your-code-climate-repo-token-for-public-repositories-on-travis-ci)

**Comment by bugtender** [comment]
Did the token has been encrypted ?
Because I found [this](http://stackoverflow.com/questions/23666020/is-it-safe-to-keep-codeclimate-repo-token-in-public-access) in StackOverflow. :smiley:

**Comment by JuanitoFatas** [comment]
@puff-tw @viflin Thanks for your review and concern. This is actually fine, please see [here](http://docs.codeclimate.com/article/276-should-i-keep-my-test-coverage-token-secret) for more details.

**Comment by bugtender** [comment]
:ok_hand:

**Pull request merged**
