### PR TITLE
Feature/add home controller test

### LINKED ISSUE #30: Write a Controller Spec
- 1. Let's rename the controller as `HomeController` instead of `StaticPagesController`
- 2. Write a spec to ensure that Home#welcome is success.

### PR DESCRIPTION
**Pull request by azi**
close #30

### CODE REVIEW

**Comment by AnNOtis** [comment]
:+1:

**Comment by sunkai612** [comment]
:+1:

**Comment by JuanitoFatas** [comment]
@sunkai612 Whoever merge a Pull Request, don't forget to give some praises for the hardwork! 

@azi :clap: :clap: :clap: :clap:

**Comment by sunkai612** [comment]
@JuanitoFatas thanks for your remind :smile: 

@azi nice job :+1:

**Pull request merged**
