### PR TITLE
Bundle Update on 2015-10-03

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**
- Updated: [kramdown](http://github.com/gettalong/kramdown), [1.8.0...1.9.0](https://github.com/gettalong/kramdown/compare/v1.8.0...v1.9.0)
- Updated: [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers), [2.8.0...3.0.0](https://github.com/thoughtbot/shoulda-matchers/compare/v2.8.0...v3.0.0) ([CHANGELOG](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md))
## 

Brought to you by [deppbot](https://www.deppbot.com).

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
@rubytaiwan/rubyists Anyone wants to fix this one? :smile:

**Comment by AnNOtis** [comment]
Please have a look.

**Comment by JuanitoFatas** [comment]
> Please have a look.

Thanks! Since you're a collaborator, next time just fix it in this Pull Request :wink:

**Comment by AnNOtis** [comment]
Okay, no problem! 😃

**Comment by JuanitoFatas** [comment]
> Okay, no problem! 😃

Wah. I wasn't looking carefully, should have merged this one. Sorry Otis!

**Pull request closed without merging**
